# Site settings

title: Scott Hacker
description: A simple resume and portfolio site built in Jekyll
email: Scott@Scott-Hacker.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scott-hacker.com" # the base hostname & protocol for your site
github_username:  ScottHacker
linkedin: https://www.linkedin.com/pub/scott-hacker/24/748/627
pages: resume
include: [images, resources]



# Build settings

markdown: kramdown
highlighter: pygments
encoding: utf-8